### ISSUE TITLE
Run Problems

### ISSUE THREAD

**Issue by vivekaxl** [ai-se/SuperCharger#2]
### Problems:
- [x] POMX
- [x] XOMO
### Number of Generations:
- [ ] 10
- [x] 100
- [ ] 1000

**Comment by vivekaxl** [comment]
![figure03_pom3a_igd](https://cloud.githubusercontent.com/assets/6147456/13587281/23986ce4-e495-11e5-9755-2e5c8912db26.png)
![figure04_pom3b_igd](https://cloud.githubusercontent.com/assets/6147456/13587282/23993f8e-e495-11e5-8e4d-d8f653ada912.png)
![figure03_pom3c_igd](https://cloud.githubusercontent.com/assets/6147456/13587285/239b38d4-e495-11e5-9212-4c032cc5979f.png)

## ![figure04_pom3d_igd](https://cloud.githubusercontent.com/assets/6147456/13587283/23997620-e495-11e5-9bb7-4b7287165783.png)

![figure05_xomo_ground_igd](https://cloud.githubusercontent.com/assets/6147456/13587284/239a273c-e495-11e5-8715-9e9d35f8372e.png)
![figure06_xomo_flight_igd](https://cloud.githubusercontent.com/assets/6147456/13587286/239fabbc-e495-11e5-9e77-5a359c643276.png)
![figure07_xomo_all_igd](https://cloud.githubusercontent.com/assets/6147456/13587288/23a3e150-e495-11e5-95bd-9ed68b932a5f.png)
![figure08_xomoo2_igd](https://cloud.githubusercontent.com/assets/6147456/13587289/23a4028e-e495-11e5-9fd6-8706437470bd.png)
![figure09_xomo_osp_igd](https://cloud.githubusercontent.com/assets/6147456/13587287/23a0ae40-e495-11e5-8ad4-df2dd0a7f62a.png)

**Comment by timm** [comment]
do i have  this right?
-  overall,  moeadd better than nsga3
- we smile if dashed below solid?
- one frown in 18 runs
          : nsga3 for pom3b; 
           other than than, no downside.
-  several big wins: 
          : moead: pom3a, pom3b, pom3d;
          nsga3: pom3c,pom3d, xomo-osp
-  ties: 
          : moead+nsga3: xoxo ground, xoxo flight xoxo all xomoo2;
          nsga3: nsga3

**Comment by timm** [comment]
Not this is one run for each, right? not N repeats?

**Comment by timm** [comment]
did you see my comment in #1: need spread and moea/d to be compatible with rest of paper

**Comment by timm** [comment]
in all the above, random sually  starts at nearly the same place as sway.. which is NOT what I'd expect (i'd have expected the pattern in pom3d where sway does better at initial point)

**Comment by timm** [comment]
how to explain the observation that LATER in the run, the sway-based optimizations do better? like sway's better information content takes some time to EMERGE from the pack?

**Comment by vivekaxl** [comment]
overall, moeadd better than nsga3 :+1: 
we smile if dashed below solid? :+1: 
one frown in 18 runs : nsga3 for pom3b; other than than, no downside. :+1: 
several big wins: : moead: pom3a, pom3b, pom3d; nsga3: pom3c,pom3d, xomo-osp :+1: 
ties: : moead+nsga3: xoxo ground, xoxo flight xoxo all xomoo2; nsga3: nsga3  :+1: 

Not this is one run for each, right? not N repeats? 5 repeats - 100 generations

did you see my comment in #1: need spread and moea/d to be compatible with rest of paper: Working on it. 

> in all the above, random sually starts at nearly the same place as sway.. which is NOT what I'd expect (i'd have expected the pattern in pom3d where sway does better at initial point)

 I agree. Currently, I am looking at how I calculate the scores and will regenerate the graphs..just to be sure if there are any bugs in my code.

> how to explain the observation that LATER in the run, the sway-based optimizations do better? like sway's better information content takes some time to EMERGE from the pack?

I need to think about it.

**Comment by vivekaxl** [comment]
[SWAY_and_MOEA.rtfd.zip](https://github.com/ai-se/SuperCharger/files/163904/SWAY_and_MOEA.rtfd.zip)

**Comment by timm** [comment]
huh. lets talk to these tomorrow

**Comment by vivekaxl** [comment]
Can't see any considerable difference. Abandoning the current thought.
